import { useApi } from 'hugo-api';

// GET /api/docs, generated by the server from its live route tree (apps/server/src/modules/docs).
export type ApiRoute = {
  method: string; path: string; params: string[]; auth: 'public' | 'optional' | 'user' | 'admin';
  rateLimited: boolean; upload: boolean; summary: string | null; notes?: string;
  query?: Record<string, string>; body?: Record<string, string>; returns?: string; errors?: Record<string, string>;
};
export type ApiGroup = { prefix: string; title: string; description?: string; guide?: string; tier?: string; routes: ApiRoute[] };
export type ApiDocs = {
  generatedAt: string;
  guide: { id: string; title: string; icon: string; body: string }[];
  groups: ApiGroup[];
  socketEvents: { dir: string; name: string; auth?: string; summary: string; payload: string }[];
};

/** URL key of a group: /api/songs → songs. */
export const groupKey = (g: ApiGroup) => g.prefix.split('/').pop() as string;

export function useApiDocs() {
  const { data, error } = useApi<ApiDocs>('GET /api/docs');
  return { data, error: error?.message ?? null };
}
