// Endpoint union for hugo-api: editors autocomplete call('…')/useApi('…') and the compiler rejects typos.
function endpointTypes(groups, { module = 'hugo-api' } = {}) {
  const lines = [...new Set(groups.flatMap((g) => g.routes.map((r) => `${r.method} ${r.path}`)))].sort();
  return `// GENERATED by \`hugo-server types\` from the server's route tree — do not edit.
declare module '${module}' {
  interface Register {
    endpoints:
${lines.map((l) => `      | '${l}'`).join('\n')};
  }
}
export {};
`;
}

module.exports = { endpointTypes };
